### ISSUE TITLE
IDE: add support for multiplexer capelet command line

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#60] opened 2016-08-06 11:41 UTC
Available options
```
-X 0 
-X 2 
-X 4
-X 8
```

**Comment by apmcpherson** [comment] 2016-08-06 15:13
Duplicate of #57.

-X 0 is the same as not specifying -X at all.

**Closed by apmcpherson** 2016-08-06 15:13 UTC
Labels: IDE

**Comment by giuliomoro** [comment] 2016-08-07 00:09
UOPS! sorry for  the dupe
