### ISSUE TITLE
Unable to upload WAV files larger than 50mb to IDE 

### ISSUE THREAD

**Issue by thenicolaslewis** [BelaPlatform/Bela#526] opened 2019-01-07 13:51 UTC
I might be missing something obvious, but every time I try to upload a larger wav file to the IDE, the Bela restarts and doesn't complete the upload. 

It works if I compress the larger files to 8-bit audio, but I would ideally like each of them to be at least 16-bit. Each file is around 56mb uncompressed.

Any suggestions or help would be really appreciated!

**Comment by giuliomoro** [comment] 2019-01-07 17:58
Duplicate of https://github.com/BelaPlatform/Bela/issues/276. Please use the `scp` command from a terminal instead, e.g.:

```
scp path/to/file.wav root@192.168.7.2:Bela/projects/projectName/
```

(or use 192.168.6.2 above if that is the IP address of your board)

**Closed by giuliomoro** 2019-01-07 17:58 UTC

**Comment by thenicolaslewis** [comment] 2019-01-07 18:53
Thats perfect, thank you!!
