### ISSUE TITLE
IDE console breaks using certain linux commands...

### ISSUE THREAD

**Issue by lewiswolf** [BelaPlatform/Bela#655] opened 2021-02-06 17:46 UTC
Hey, I had a go at fixing this myself but to no avail. 

If you type _vim_ or _vi_ in the browser IDE console, you're completely locked out of the console until you restart the Bela.

**Comment by giuliomoro** [comment] 2021-02-06 19:00
yes that's not what it's meant for... it's not an actual terminal, it's just an instance of bash processing the commands you type in ...

Duplicate of #16 . See [here](https://github.com/BelaPlatform/Bela/issues/16#issuecomment-377734720) for an alternative I looked into 3 years ago ... if that still works and you have some time we could try and incorporate it in the IDE :)

Closing this issue, keep the ensuing discussion (if any) on #16 please.

**Closed by giuliomoro** 2021-02-06 19:00 UTC
