### ISSUE TITLE
IDE: 'more' breaks the console

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#619] opened 2020-03-29 19:58 UTC
Running the `more` command in the console at the bottom of the IDE causes it to hang. No result is apparently returned and no further commands work, even after reloading the page.

**Comment by giuliomoro** [comment] 2020-03-30 07:43
duplicate of https://github.com/BelaPlatform/Bela/issues/16 , where I also suggest a solution "xterm.js"

**Closed by giuliomoro** 2020-03-30 07:43 UTC
