### ISSUE TITLE
IDE: using fewer than 3 scope channels causes crash

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#188] opened 2016-10-23 22:59 UTC
If a Bela program uses 1 or 2 scope channels, and the scope tab is already open when program launches, a seg fault results.

If the scope tab is closed on launch but opened later, it runs fine. If the program uses 3 or more channels, it runs fine either way.

This is most easily demonstrated with `ultrasonic-distance` example, but it can be reproduced by reducing the number of scope channels in `scope-analog` to 2 or 1, with the same result.

**Comment by LBDonovan** [comment] 2016-10-24 05:34
I can't reproduce this. Are you sure you were setting the number of channels correctly in `scope.setup()`?

If you get the chance, could you try this again after ssh'ing to the board and running `screen -r` to see node's output, and pressing cmd+alt+j in the scope window in chrome to see its console?

**Comment by LBDonovan** [comment] 2016-10-24 12:26
So it appears this happens very rarely indeed, possibly only after messing with the settings, closing and reopening tabs, and reducing the number of channels, but it's very hard to reproduce.

We should check Scope.cpp for race conditions.

**Comment by LBDonovan** [comment] 2016-10-25 09:08
@giuliomoro I wonder if https://github.com/BelaPlatform/Bela/blob/master/core/Scope.cpp#L158 could be the problem here - the window buffer is created with new but never deleted.

I also think it might be a good idea to pass the parameter `true` to `start()` here: https://github.com/BelaPlatform/Bela/blob/master/core/Scope.cpp#L534

That would force `plotMode()` to run synchronously on the OSC receive aux task rather than scheduling it to happen later. In fact, I have a vague memory (it was a while ago) of encountering an occasional bug where scheduling an aux task while on an aux task occasionally didn't work, I wonder if that might be the source of this issue?

**Comment by LBDonovan** [comment] 2016-10-25 09:11
Actually all the FFT buffers are never freed as far as I can tell. Shouldn't that be changed?

**Comment by giuliomoro** [comment] 2016-10-25 10:21
The `NE10_FREE`s have been added by 66456c4acb59277b02344ae9a7a627d11a4110a8 to replace `delete`and removed by cc006c92fa6b10ed78b4fb3935a9dd6c0425e863   but were not added back in ...
 I guess I forgot them ...

**Closed** 2017-12-19 23:30 UTC
Labels: bug
