### ISSUE TITLE
IDE: autoscroll is inconsistent during long builds

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#186] opened 2016-10-23 22:34 UTC
After `make coreclean` or a long build like `d-box`, the log at the bottom does not scroll consistently with new text. Sometimes several files will build and the log will be off the bottom, only for the display to jump back to the right place a few lines later. The result is that without manually scrolling, you can't tell if one file is taking a long time to build or whether there are others being built.

**Comment by giuliomoro** [comment] 2016-10-23 22:41
were you scrolled all the way to the bottom to being with?

**Comment by apmcpherson** [comment] 2016-10-23 22:46
Yes. I tried three cases: don't touch it at all (starting from clean console); scroll down to the bottom so that the terminal pops up; scroll down to the last output but not including the terminal. Same behaviour, though not consistent, happens each time.

Sometimes it will start scrolling correctly for a while, only to stop for a while and jump back to the bottom sometime later. Sometimes the log will obscure the terminal line, sometimes not.

**Comment by apmcpherson** [comment] 2016-10-23 23:00
Same behaviour applies to output generated from the Bela program. For example, see `FFT-phase-vocoder`.

**Comment by giuliomoro** [comment] 2016-10-23 23:40
may be related with this https://github.com/BelaPlatform/Bela/issues/15

**Comment by LBDonovan** [comment] 2016-10-24 05:41
Ok so this is intended behaviour at the moment, though it could change. 

What happens is, if you scroll the console off the bottom manually the autoscroll gets turned off, so the user has control of the console's scroll (as in #15 ). This is true until either an error appears (i.e a console entry which is red or yellow - this includes Bela's stderr) or a notification appears (a console entry which starts off green and then fades to white and (for some) disappears, e.g Building Project, Build Finished, Running Project, Stopping Bela etc).

My rational is that you wouldn't want to miss it when one of these happens, so it should be scrolled into view. But I get how it can be annoying, it annoys me sometimes. I could easily turn this off, and just switch the autoscroll off for good when the user scrolls up...

**Comment by LBDonovan** [comment] 2016-10-24 05:46
Is there any consistency to when the console obscures the terminal prompt? Are you on Chrome?

**Comment by LBDonovan** [comment] 2016-10-24 05:50
Actually, I can't reproduce the build log scrolling out of view during a core build. Are you manually scrolling the console at all?

**Comment by LBDonovan** [comment] 2016-10-24 09:47
Ok, found the problem.

There is a bug with chrome where it doesn't report the scroll position properly if the user has zoomed away from 100%. It can be fixed by pressing cmd+0. I had a go at fixing it but it's not trivial, I would suggest we leave it for this image and revisit it later.

**Comment by giuliomoro** [comment] 2017-06-20 22:59
So this is a Chrome issue. Make sure zoom is 100%. Closed.

**Closed by giuliomoro** 2017-06-20 22:59 UTC
Labels: bug
