### ISSUE TITLE
WARNING: [mError opening plugin directory '/usr/local/lib/csound/plugins-6.0': No such file or directory[m

### ISSUE THREAD

**Issue by csounder** [BelaPlatform/Bela#639] opened 2020-07-04 08:32 UTC
In the Bela console, when running Csound, this warning "always" appears - and it might explain a number of the "missing" opcodes?  Perhaps, the plugins are located in a different folder, and are installed on the Bela?  Hope so.  Please advise on how to find them and eliminate this warning message.  And THANKS!!!  Dr.B.

**Comment by csounder** [comment] 2020-07-04 09:10
Victor Lazzarini told me that "this"warning might explain the "missing opcodes" from the currently built version of Csound for the Bela.  He said:

Yes, that could be the issue. Csound is probably installed somewhere else; that is the default plugin directory. The environment variables OPCODE6DIR64 or OPCODE6DIR can be used to fix this."

**Comment by giuliomoro** [comment] 2020-07-04 15:03
This also is a duplicate of https://github.com/BelaPlatform/Bela/issues/612 , and I asked a question there twice, without getting any answer. If you could please continue the conversation there, that'd be great.

**Closed by giuliomoro** 2020-07-04 15:03 UTC

**Comment by csounder** [comment] 2020-07-04 15:14
Sorry about repeating the question again.  At the time, I was reporting a warning that was not behind some bugs that I was experiencing, now, my students are puzzled by missing opcodes in Csound on the Bela which are there on Csound for the Mac.  I will ask there and continue the dialogue there.  

Best person to answer some of the where are the parts of Csound installed is Victor Lazzarini 

He responded to me/you with the advice "that 'make install' should install the plugins in that directory, unless the install prefix setting of CMake is used to install Csound somewhere else. 

I don't know where they install Csound. I am also not quite sure what plugins are being built, some have external dependencies and may not be present. "

Prof. Victor Lazzarini
Maynooth University
Ireland

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by giuliomoro** [comment] 2020-07-04 15:20
please see my comment on #612
